learning_rate: 0.001
gamma: 0.99
epsilon_start: 1.0
epsilon_end: 0.01
epsilon_decay: 0.995
buffer_size: 100000
batch_size: 32
target_update: 1000
num_episodes: 5000
max_steps: 200
render: false
save_model_freq: 1000
model_path: "models/dqn_model.h5"