learning_rate: 0.0003
gamma: 0.99
n_steps: 2048
batch_size: 64
n_epochs: 10
clip_range: 0.2
ent_coef: 0.01
vf_coef: 0.5
max_grad_norm: 0.5
gae_lambda: 0.95
target_kl: 0.01
learning_rate_schedule: "linear"
log_interval: 10
save_interval: 10000
total_timesteps: 1000000